package core

import "github.com/nuttaponsrpn/go-splendor/gotype"

var DevelopmentLevel1 = []gotype.DevelopmentCard{
	{
		ID:      1,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 0, Emerald: 2, Ruby: 2, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      2,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 1, Ruby: 3, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      3,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 1, Emerald: 3, Ruby: 1, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      4,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 2, Emerald: 1, Ruby: 1, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      5,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 1, Emerald: 0, Ruby: 1, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      6,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 1, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      7,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 0, Emerald: 1, Ruby: 1, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      8,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 3, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      9,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 2, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      10,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 1, Emerald: 1, Ruby: 1, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      11,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 2, Ruby: 0, Onyx: 2, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      12,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 1, Emerald: 0, Ruby: 2, Onyx: 2, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      13,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 1, Emerald: 1, Ruby: 0, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      14,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 3, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      15,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 2, Ruby: 1, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      16,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 1, Emerald: 1, Ruby: 1, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      17,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 4, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Ruby,
	},
	{
		ID:      18,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 1, Emerald: 0, Ruby: 0, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      19,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 4, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Diamond,
	},
	{
		ID:      20,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 0, Emerald: 1, Ruby: 2, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      21,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 0, Ruby: 2, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      22,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 2, Ruby: 0, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      23,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 0, Emerald: 2, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      24,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 0, Emerald: 2, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      25,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 1, Emerald: 0, Ruby: 1, Onyx: 2, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      26,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      27,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      28,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 1, Emerald: 2, Ruby: 1, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      29,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 3, Joker: 0},
		Points:  0,
		GemType: gotype.Sapphire,
	},
	{
		ID:      30,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 2, Emerald: 0, Ruby: 1, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      31,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 0, Emerald: 0, Ruby: 1, Onyx: 3, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      32,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 0, Ruby: 0, Onyx: 2, Joker: 0},
		Points:  0,
		GemType: gotype.Diamond,
	},
	{
		ID:      33,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 1, Emerald: 1, Ruby: 0, Onyx: 1, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      34,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 4, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Sapphire,
	},
	{
		ID:      35,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 1, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      36,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 3, Emerald: 1, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Emerald,
	},
	{
		ID:      37,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 4, Joker: 0},
		Points:  0,
		GemType: gotype.Onyx,
	},
	{
		ID:      38,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 0, Emerald: 1, Ruby: 0, Onyx: 2, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
	{
		ID:      39,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 4, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Onyx,
	},
	{
		ID:      40,
		Level:   1,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 0, Emerald: 0, Ruby: 2, Onyx: 0, Joker: 0},
		Points:  0,
		GemType: gotype.Ruby,
	},
}

var DevelopmentLevel2 = []gotype.DevelopmentCard{
	{
		ID:      1,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 5, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Diamond,
	},
	{
		ID:      2,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 3, Ruby: 0, Onyx: 2, Joker: 0},
		Points:  1,
		GemType: gotype.Onyx,
	},
	{
		ID:      3,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 3, Emerald: 0, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Diamond,
	},
	{
		ID:      4,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 2, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Sapphire,
	},
	{
		ID:      5,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 6, Onyx: 0, Joker: 0},
		Points:  3,
		GemType: gotype.Ruby,
	},
	{
		ID:      6,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 1, Sapphire: 4, Emerald: 2, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Ruby,
	},
	{
		ID:      7,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 3, Emerald: 0, Ruby: 2, Onyx: 3, Joker: 0},
		Points:  1,
		GemType: gotype.Ruby,
	},
	{
		ID:      8,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 2, Emerald: 3, Ruby: 0, Onyx: 3, Joker: 0},
		Points:  1,
		GemType: gotype.Sapphire,
	},
	{
		ID:      9,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 6, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  3,
		GemType: gotype.Sapphire,
	},
	{
		ID:      10,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 6, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  3,
		GemType: gotype.Diamond,
	},
	{
		ID:      11,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 2, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Emerald,
	},
	{
		ID:      12,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 4, Sapphire: 2, Emerald: 0, Ruby: 0, Onyx: 1, Joker: 0},
		Points:  2,
		GemType: gotype.Emerald,
	},
	{
		ID:      13,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 5, Joker: 0},
		Points:  2,
		GemType: gotype.Ruby,
	},
	{
		ID:      14,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 3, Ruby: 2, Onyx: 3, Joker: 0},
		Points:  1,
		GemType: gotype.Diamond,
	},
	{
		ID:      15,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 2, Emerald: 2, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  1,
		GemType: gotype.Onyx,
	},
	{
		ID:      16,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 3, Emerald: 0, Ruby: 0, Onyx: 2, Joker: 0},
		Points:  1,
		GemType: gotype.Emerald,
	},
	{
		ID:      17,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 5, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Emerald,
	},
	{
		ID:      18,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 1, Emerald: 4, Ruby: 2, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Onyx,
	},
	{
		ID:      19,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 5, Emerald: 3, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Emerald,
	},
	{
		ID:      20,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 0, Emerald: 0, Ruby: 1, Onyx: 4, Joker: 0},
		Points:  2,
		GemType: gotype.Sapphire,
	},
	{
		ID:      21,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 5, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Onyx,
	},
	{
		ID:      22,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 5, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Sapphire,
	},
	{
		ID:      23,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 5, Sapphire: 3, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Sapphire,
	},
	{
		ID:      24,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 6, Joker: 0},
		Points:  3,
		GemType: gotype.Onyx,
	},
	{
		ID:      25,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 6, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  3,
		GemType: gotype.Emerald,
	},
	{
		ID:      26,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 5, Joker: 0},
		Points:  2,
		GemType: gotype.Ruby,
	},
	{
		ID:      27,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 1, Ruby: 4, Onyx: 2, Joker: 0},
		Points:  2,
		GemType: gotype.Diamond,
	},
	{
		ID:      28,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 5, Onyx: 3, Joker: 0},
		Points:  2,
		GemType: gotype.Diamond,
	},
	{
		ID:      29,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 5, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  2,
		GemType: gotype.Onyx,
	},
	{
		ID:      30,
		Level:   2,
		Cost:    gotype.Gems{Diamond: 2, Sapphire: 0, Emerald: 0, Ruby: 2, Onyx: 3, Joker: 0},
		Points:  1,
		GemType: gotype.Ruby,
	},
}

var DevelopmentLevel3 = []gotype.DevelopmentCard{
	{
		ID:      1,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 6, Sapphire: 3, Emerald: 0, Ruby: 0, Onyx: 3, Joker: 0},
		Points:  4,
		GemType: gotype.Sapphire,
	},
	{
		ID:      2,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 5, Emerald: 3, Ruby: 0, Onyx: 3, Joker: 0},
		Points:  3,
		GemType: gotype.Ruby,
	},
	{
		ID:      3,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 6, Emerald: 3, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Emerald,
	},
	{
		ID:      4,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 3, Ruby: 3, Onyx: 5, Joker: 0},
		Points:  3,
		GemType: gotype.Sapphire,
	},
	{
		ID:      5,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 7, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  5,
		GemType: gotype.Ruby,
	},
	{
		ID:      6,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 7, Joker: 0},
		Points:  4,
		GemType: gotype.Diamond,
	},
	{
		ID:      7,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 7, Joker: 0},
		Points:  5,
		GemType: gotype.Diamond,
	},
	{
		ID:      8,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 7, Onyx: 3, Joker: 0},
		Points:  5,
		GemType: gotype.Onyx,
	},
	{
		ID:      9,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 0, Ruby: 7, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Onyx,
	},
	{
		ID:      10,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 7, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Emerald,
	},
	{
		ID:      11,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 7, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Emerald,
	},
	{
		ID:      12,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 7, Emerald: 3, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  5,
		GemType: gotype.Emerald,
	},
	{
		ID:      13,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 7, Sapphire: 0, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Sapphire,
	},
	{
		ID:      14,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 3, Emerald: 6, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  4,
		GemType: gotype.Ruby,
	},
	{
		ID:      15,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 3, Emerald: 5, Ruby: 3, Onyx: 0, Joker: 0},
		Points:  3,
		GemType: gotype.Onyx,
	},
	{
		ID:      16,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 3, Sapphire: 0, Emerald: 0, Ruby: 3, Onyx: 6, Joker: 0},
		Points:  4,
		GemType: gotype.Diamond,
	},
	{
		ID:      17,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 7, Sapphire: 3, Emerald: 0, Ruby: 0, Onyx: 0, Joker: 0},
		Points:  5,
		GemType: gotype.Sapphire,
	},
	{
		ID:      18,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 3, Emerald: 3, Ruby: 5, Onyx: 3, Joker: 0},
		Points:  3,
		GemType: gotype.Diamond,
	},
	{
		ID:      19,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 5, Sapphire: 3, Emerald: 0, Ruby: 3, Onyx: 3, Joker: 0},
		Points:  3,
		GemType: gotype.Emerald,
	},
	{
		ID:      20,
		Level:   3,
		Cost:    gotype.Gems{Diamond: 0, Sapphire: 0, Emerald: 3, Ruby: 6, Onyx: 3, Joker: 0},
		Points:  4,
		GemType: gotype.Onyx,
	},
}

var Nobles = []gotype.NobleCard{
	{
		ID:     1,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 4, gotype.Sapphire: 0, gotype.Emerald: 0, gotype.Ruby: 0, gotype.Onyx: 4, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     2,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 0, gotype.Sapphire: 3, gotype.Emerald: 3, gotype.Ruby: 3, gotype.Onyx: 0, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     3,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 3, gotype.Sapphire: 3, gotype.Emerald: 0, gotype.Ruby: 0, gotype.Onyx: 3, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     4,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 0, gotype.Sapphire: 4, gotype.Emerald: 4, gotype.Ruby: 0, gotype.Onyx: 0, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     5,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 4, gotype.Sapphire: 4, gotype.Emerald: 0, gotype.Ruby: 0, gotype.Onyx: 0, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     6,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 0, gotype.Sapphire: 0, gotype.Emerald: 4, gotype.Ruby: 4, gotype.Onyx: 0, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     7,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 3, gotype.Sapphire: 0, gotype.Emerald: 0, gotype.Ruby: 3, gotype.Onyx: 3, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     8,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 0, gotype.Sapphire: 0, gotype.Emerald: 3, gotype.Ruby: 3, gotype.Onyx: 3, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     9,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 3, gotype.Sapphire: 3, gotype.Emerald: 3, gotype.Ruby: 0, gotype.Onyx: 0, gotype.Joker: 0},
		Points: 3,
	},
	{
		ID:     10,
		Cost:   map[gotype.GemType]int{gotype.Diamond: 0, gotype.Sapphire: 0, gotype.Emerald: 0, gotype.Ruby: 4, gotype.Onyx: 4, gotype.Joker: 0},
		Points: 3,
	},
}
